name: Test and Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    container: cypress/base:14.17.0 
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: install yarn
      run: npm install -g yarn
    
    - name: Install dependencies
      run: yarn install

    - name: Lint 
      run: yarn lint:api && yarn lint:client
    
    - name: Test api
      env: 
        TEST_MONGODB_URI: ${{secrets.MONGODB_URI}}
      run: yarn test:api
      

    - name: Build
      run: yarn build

    - name: E2E tests for production mode
      env: 
        MONGODB_URI: ${{secrets.MONGODB_URI}}
        PORT: 3003
      uses: cypress-io/github-action@v2
      with:
        start: yarn api:prod
        wait-on: 'http://localhost:3003'
        command: yarn cypress:run

    - name: heroku deployment
      uses: akhileshns/heroku-deploy@v3.12.12
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "fso-pro"
        heroku_email: "akuankka75@gmail.com"
        healthcheck: "https://fso-pro.herokuapp.com/health"
        checkstring: "ok"
        rollbackonhealthcheckfailed: true

